version: '3'

volumes:
  pgdata:
  appdata:
  grafdata:
  promdata:

services:
  app:
    image: capas/game-repository:latest
    ports:
      - 3000:3000/tcp
    volumes:
      - appdata:/app/data
      - ./config.docker.json:/app/config.json
    depends_on:
      - db
  db:
    image: postgres:14-alpine3.17
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # reference https://github.com/prometheus/prometheus/blob/main/Dockerfile
      - promdata:/prometheus
    ports:
      - 3330:9090

  grafana:
    image: grafana/grafana
    ports:
      - 3300:3000/tcp
    volumes:
      - grafdata:/var/lib/grafana

  
