site_name: Game repository 
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  
  language: it
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo 
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: indigo
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


copyright: |
  &copy; <a href="https://github.com/alarmfox"  target="_blank" rel="noopener">Giuseppe Capasso</a> <br>
  &copy; <a href="https://github.com/alarmfox"  target="_blank" rel="noopener">Pasquale Angelino</a> <br>
  &copy; <a href="https://github.com/alarmfox"  target="_blank" rel="noopener">Andrea Dinetti</a> <br>

