name: cd

on:
  push:
    branches: [ "stage" ]
    paths-ignore:
      - 'README.md'
      - 'vendor/**'
      - 'postman/**'
      - '.postman/**'
      - Makefile
      - LICENSE
      - 'docs/**'
      
  pull_request:
    branches: [ "stage" ]
    paths-ignore:
      - 'README.md'
      - 'vendor/**'
      - 'postman/**'
      - '.postman/**'
      - Makefile
      - LICENSE
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/game-repository:latest
