# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'vendor/**'
      - 'postman/**'
      - '.postman/**'
      - Makefile
      - LICENSE
      
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - 'vendor/**'
      - 'postman/**'
      - '.postman/**'
      - Makefile
      - LICENSE
      
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: make build

    - name: Run Test
      run: |
        make test    
        
